Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'applications')

src = Split("""
application.c
startup.c
App_LDS_Protocol.c
app_test_drv.c
Service_rs485.c
""")

if GetDepend('RT_USING_CAN'):
    src += ['canapp.c']

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
